version: '3.4'

services:
    mariadb:
        container_name: cake-store-mariadb
        image: mariadb:10.3
        env_file:
            - ./.env
        restart: always
        networks:
            - cake-store-api-net
        ports:
            - "${MARIADB_PORT}:3306"
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./data/mariadb:/var/lib/mysql
networks:
    cake-store-api-net: {}